# baseURL = 'https://braidyndbcdatabase.netlify.app'
# baseURL = 'https://braidyn-bc.github.io/bdbc-website/'
# baseURL = 'https://braidyn-bc.github.io/'
# baseURL = '/'
languageCode = 'ja-jp'
title = 'BraiDyn-BC Database'
theme = "hugo-bootstrap-theme"
themesdir = "node_modules/@filipecarneiro"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false
disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"