# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
description = ""
mainMenuLogo = "images/logo.png"

# For favicons
## Chrome Browser
themeColor = "#fff"

# Alert
# alert = false
# alertDismissable = true
# alertText = ""

[options]
  bootStrapJs = true
  breadCrumb = true
  listTagFilter = true
