baseURL = 'https://boatneck-weeder-7b7.notion.site/BraiDyn-BC-Database-1e972fb17ad1470b911aa108fb8c0713'
languageCode = 'en-us'
title = 'BraiDyn-BC Database'
theme = "hugo-bootstrap-theme"
themesdir = "node_modules/@filipecarneiro"